### ISSUE TITLE
Scatter plot needs to default off each chart plot

### ISSUE THREAD

**Issue by JakeFountain** [NUbots/NUsight#18]
It is common to have many extra bits of data which you switch between with one or two on at a time. therefore it is more convenient to have the chart streams switched to off when the window is open. 

It would be good if this also reduced performance issues with having many data streams. Maybe have a system to add the chart streams one at a time and not plot them otherwise to reduce performance issues

**Comment by Phasedd** [comment]
This was my idea to improve performance.

I tried ways to improve the performance, but I will have to disable all traces, and let the user select traces on and off.

Which way sounds the best:
1. A system similar to the chat window, where all available streams are shown on the right side of the window.
2. Extending functionality to the config menu for each stream, have a check box to turn on and off a specific stream. (As well as allow lines to be displayed individually for specific traces (will be added anyway)).

I believe option 2 would give a lot more room to allow the graph to be displayed over the entire window.

**Comment by Phasedd** [comment]
If I understood this correctly, it should be added now.

You wanted all traces to be disabled and have a way to individually add different traces to the graph?

**Comment by JakeFountain** [comment]
Yep. Thanks
