### ISSUE TITLE
Add xy scatter plot to charts

### ISSUE THREAD

**Issue by JakeFountain** [NUbots/NUsight#4]

**Comment by Phasedd** [comment]
Implemented with the ability to set a Y min and max, X min and max, max points to plot for each trace, specify what traces to show, pausing, show lines between each plot and mouse over hover data (requires the graph to be paused).

Other features from the library is zoom (if zoom is selected in the graph toolbar (top right under settings, it auto hides), you can drag on the graph to highlight where to zoom), panning (requires the graph to be paused), download the plot as a .png and upload the data to there website.
